### ISSUE TITLE
Differential calling error

### ISSUE THREAD

**Issue by sespesogil** [ay-lab/dcHiC#17]
Hi! Congrats for the nice tool!

I am a bit  puzzled at the very end of running dcHiC.py where it launches the differential calling: 

python /path/dchic/differentialCalling.py -inputFile input.txt -chrFile chromosomes.txt -multiComp 1 -makePlots 1 -res 100000 -genome mm10 -blacklist /path/dcHiC/files/mm10blacklist_sorted.bed

With the following error:
Traceback (most recent call last):
  File "/path/dchic/differentialCalling.py", line 469, in <module>
    main()
  File "/path/dchic/differentialCalling.py", line 363, in main
    checkInputs(0)
  File "/path/dchic/differentialCalling.py", line 205, in checkInputs
    names.append(temp[0])
IndexError: list index out of range

It seems that some of the files might not have the correct format. But it is strange , because the previous part of the code is running totally fine, getting the expected outputs. 

I have a couple of samples per condition. My inputs looks like:

ctl.1    CTL     /path/ctl.Rep1
ctl.2   CTL     /path/ctl.Rep2
exp.1   EXP   /path/exp.Rep1
exp.2   EXP    /path/exp.Rep2

If I include -repParams it still gives me the same error. I will really appreciate if you could clarify. Thanks in advance

Kind regards, 

S.

**Comment by sespesogil** [comment]
Hi again! I have solved it.  One of my files was a bit funky , I rerun everything from scratch and now working nice. 

Thanks!
